version: '3.9'

services:
  mysql:
    image: mysql:latest
    container_name: user_db_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: user_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "1999:3306"
